In [13]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/uganda_fake_news_v2.csv",
    skipinitialspace=True
)

print(df.shape)
df.head()

(1490, 7)

,id,text,label,source,platform_type,language,date_collected
0,UG_TRUE_201,Ekitike's Quickfire Brace Flips Liverpool's Cl...,True,BBC News,traditional_media,English,1/31/2026
1,UG_TRUE_202,Ronaldo Hits 961st Goal in Al Nassr's 3-0 Rout...,True,BBC News,traditional_media,English,1/31/2026
2,UG_TRUE_203,Minister Muyingo’s Seeta Junior gets 56 fours ...,True,Daily Monitor,traditional_media,English,2/2/2026
3,UG_TRUE_204,"High Prices, Low Turnout Mark Back-to-School R...",True,Nile Post,traditional_media,English,2/9/2026
4,UG_TRUE_205,Auditor General Slams Pornography Control Comm...,True,Nile Post,traditional_media,English,2/9/2026

In [14]:


# Check dataset shape
df.shape

(1490, 7)

In [15]:
# 
duplicates = df[df.duplicated(subset=["text"], keep=False)]
duplicates.sort_values("text").head(20)

,id,text,label,source,platform_type,language,date_collected
1305,UG_FALSE_760,Did President Boakai Faint During Speech Deliv...,False,Dubawa,Fact Check,English,2/19/2026
1333,UG_FALSE_789,Did President Boakai Faint During Speech Deliv...,False,Dubawa,Fact Check,English,2/19/2026
40,UG_TRUE_241,Odonga Otto Blasts State House Meeting as a ‘C...,True,Nile Post,traditional_media,English,2/7/2026
45,UG_TRUE_246,Odonga Otto Blasts State House Meeting as a ‘C...,True,Nile Post,traditional_media,English,2/7/2026
41,UG_TRUE_242,Questions Mount Over Delayed Operations at Kil...,True,Nile Post,traditional_media,English,2/7/2026
46,UG_TRUE_247,Questions Mount Over Delayed Operations at Kil...,True,Nile Post,traditional_media,English,2/7/2026
71,UG_TRUE_272,UCE Results: Record Pass Rates Highlight CBC G...,True,Nile Post,traditional_media,English,2/13/2026
91,UG_TRUE_292,UCE Results: Record Pass Rates Highlight CBC G...,True,Nile Post,traditional_media,English,2/14/2026
62,UG_TRUE_263,Uganda’s Economy Shows Resilience Amid Global ...,True,Daily Monitor,traditional_media,English,2/10/2026
64,UG_TRUE_265,Uganda’s Economy Shows Resilience Amid Global ...,True,Daily Monitor,traditional_media,English,2/10/2026
66,UG_TRUE_267,Uganda’s Economy Shows Resilience Amid Global ...,True,Daily Monitor,traditional_media,English,2/10/2026
68,UG_TRUE_269,Uganda’s Economy Shows Resilience Amid Global ...,True,Daily Monitor,traditional_media,English,2/10/2026
839,UG_FALSE_290,Weekly round-up: Trending claims DUBAWA verifi...,False,Dubawa,Fact Check,English,2/19/2026
1218,UG_FALSE_673,Weekly round-up: Trending claims DUBAWA verifi...,False,Dubawa,Fact Check,English,2/19/2026

In [16]:


#Check for missing values
df['label'].value_counts()

df.duplicated().sum()
df = df.drop_duplicates()

df['text_length'] = df['text'].str.split().str.len()

df['text_length'].describe()

count    1490.000000
mean       12.142282
std         3.843465
min         4.000000
25%         9.000000
50%        12.000000
75%        14.000000
max        34.000000
Name: text_length, dtype: float64

In [17]:
# 
df.duplicated(subset=["text"]).sum()

np.int64(8)

In [18]:
df = df.drop_duplicates(subset=["text"])

In [19]:
df.duplicated(subset=["text"]).sum()

np.int64(0)

In [20]:
dup_counts = df["text"].value_counts()
dup_counts[dup_counts > 1]

Series([], Name: count, dtype: int64)

In [21]:
# Confirming dataset shape
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1482
Columns: 8

In [22]:
# checking no structural null explosion
df.isnull().sum()

id                0
text              0
label             0
source            0
platform_type     0
language          0
date_collected    0
text_length       0
dtype: int64

In [23]:


# confirming platform types
df["platform_type"].value_counts()

platform_type
traditional_media    744
Fact Check           738
Name: count, dtype: int64

In [24]:
# checking label distribution/ text sanity check
df.sample(5)[["text", "label"]]

                                                   text  label
1325  False! No giant statue exists in New England V...  False
755   2027 elections: Footage of crowd queuing for b...  False
1043  Budget for Liberia National Police in 2026 dra...  False
583   Bannamateeka 41 bebasunsuddwa kooti y’amagye o...   True
184   Police ekutte abantu 4 abagambibwa okumenya ek...   True

In [25]:
# Save cleaned dataset
df.to_csv("../data/processed/uganda_fake_news_v2_cleaned.csv", index=False)

In [26]:

# Verify saved file
df_check = pd.read_csv("../data/processed/uganda_fake_news_v2_cleaned.csv")
df_check.head()

,id,text,label,source,platform_type,language,date_collected,text_length
0,UG_TRUE_201,Ekitike's Quickfire Brace Flips Liverpool's Cl...,True,BBC News,traditional_media,English,1/31/2026,8
1,UG_TRUE_202,Ronaldo Hits 961st Goal in Al Nassr's 3-0 Rout...,True,BBC News,traditional_media,English,1/31/2026,12
2,UG_TRUE_203,Minister Muyingo’s Seeta Junior gets 56 fours ...,True,Daily Monitor,traditional_media,English,2/2/2026,15
3,UG_TRUE_204,"High Prices, Low Turnout Mark Back-to-School R...",True,Nile Post,traditional_media,English,2/9/2026,9
4,UG_TRUE_205,Auditor General Slams Pornography Control Comm...,True,Nile Post,traditional_media,English,2/9/2026,10